name: Deploy to Firebase

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          
      - name: Install dependencies
        run: npm install
        
      - name: Create a production build
        run: npm ci && npm run build
        env: 
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
        
      - name: Deploy the project
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
